[package]
name = "restdis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
redis = "0.23.2"
tokio = { version = "1.31.0", features = ["full"]}
